apiVersion: v1
kind: Secret
metadata:
  name: django-app-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: {{ .Values.repoUrl }}
  # Public repo - no credentials needed.
  # For private repo uncomment and set via K8s secret:
  # username: <github-user>
  # password: <github-token>
